name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DB_USER: ${{secrets.DB_USER}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_NAME: ${{secrets.DB_NAME}}
jobs:

  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag software-testing:latest
    - name: Run the testing postgres Database and initialize it.
      run: |
        docker network create test-net 
        docker run -d --network test-net --name postgres -e POSTGRES_USER=$DB_USER -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_DB=$DB_NAME -p 5432:5432 --volume "db_dump.sql:/docker-entrypoint-initdb.d/db_dump.sql" postgres
    - name: Build the project
      run: |
        npm install @nestjs/cli -g
        npm install
        npm run build
    - name: Run Unit and Integration tests
      run: |
        npm run test
    - name: Run End to End tests
      run: |
        npm run test:e2e



  
      
