name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  DB_USER: ${{secrets.DB_USER}}
  DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  DB_NAME: ${{secrets.DB_NAME}}
jobs:

  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag software-testing:latest
    - name: Run the docker images
      run: |
        docker network create test-net 
        docker run -d --network test-net --name postgres -e POSTGRES_USER=$DB_USER -e POSTGRES_PASSWORD=$DB_PASSWORD -e POSTGRES_DB=$DB_NAME postgres
        docker ps
        docker run --network test-net --name software-testing -id software-testing:latest 
        sleep 10
        docker exec -i software-testing /bin/sh -c "npm run test" 
        docker exec -i software-testing /bin/sh -c "npm run test:e2e"


  
      
